# # docker-compose.yml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env

    ports:
      - '3000:3000'
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mysqldb
      - redisdb

  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=note_taking
    ports:
      - '3307:3306'
    volumes:
        - ./migration:/docker-entrypoint-initdb.d
        - ~/var/lib/docker/volumes/mysqldb:/var/lib/mysql

  redisdb:
    container_name: redis
    image: redis:alpine
    ports:
      - '6381:6379'
